import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildGraph } from "../build/graph.js";
import { pickAtlasScopes, buildGraphPage, atlasFileName } from "../build/visualize.js";
import { callTool, resultText, tempDir } from "./helpers.mjs";

/** core/ and ui/ are imported, tests/ only imports, lonely/ has a single imported file. */
function makeProject() {
  const root = tempDir("cg-atlas-");
  const write = (rel, text) => {
    mkdirSync(join(root, rel, ".."), { recursive: true });
    writeFileSync(join(root, rel), text);
  };
  write("core/a.ts", "export const a = 1;\n");
  write("core/b.ts", 'import { a } from "./a";\nexport const b = a;\n');
  write("core/c.ts", 'import { a } from "./a";\nexport const c = a;\n');
  write("ui/x.ts", 'import { a } from "../core/a";\nimport { b } from "../core/b";\nimport { y } from "./y";\nexport const x = [a, b, y];\n');
  write("ui/y.ts", 'import { c } from "../core/c";\nexport const y = c;\n');
  write("ui/z.ts", 'import { x } from "./x";\nimport { y } from "./y";\nexport const z = [x, y];\n');
  write("tests/t1.ts", 'import { a } from "../core/a";\nimport { x } from "../ui/x";\nexport const t = [a, x];\n');
  write("lonely/only.ts", "export const only = 1;\n");
  write("main.ts", 'import { z } from "./ui/z";\nimport { a } from "./core/a";\nimport { only } from "./lonely/only";\nexport default [z, a, only];\n');
  return root;
}

test("pickAtlasScopes ranks imported directories and drops test-only and single-file ones", async () => {
  const root = makeProject();
  const graph = await buildGraph(root);

  const scopes = pickAtlasScopes(graph, root, undefined, 8);
  assert.deepEqual(scopes.map((s) => s.scope), ["core", "ui"]);
  assert.deepEqual(scopes[0], { scope: "core", files: 3, importers: 7 });
  assert.deepEqual(scopes[1], { scope: "ui", files: 3, importers: 5 });

  assert.deepEqual(pickAtlasScopes(graph, root, undefined, 1).map((s) => s.scope), ["core"]);
  assert.deepEqual(pickAtlasScopes(graph, root, "ui", 8), [], "ui/ has no subdirectories");
  assert.equal(atlasFileName("apps/desktop/src"), "apps_desktop_src.html");
});

test("buildGraphPage restricts to the scope and escapes file names", async () => {
  const root = makeProject();
  writeFileSync(join(root, "core", "we<ird>.ts"), "export const w = 1;\n");
  writeFileSync(join(root, "core", "user.ts"), 'import { w } from "./we<ird>";\nexport const u = w;\n');
  const graph = await buildGraph(root);

  const page = buildGraphPage(graph, root, { scope: "core", top: 10, backLink: "index.html" });
  assert.deepEqual(page.topFiles[0], ["core/a.ts", 5]);
  assert.ok(page.topFiles.every(([file]) => file.startsWith("core/")));
  assert.match(page.html, /href="index\.html"/);
  assert.match(page.html, /<button id="live"[^>]*aria-pressed="false"/, "live layout toggle starts off");
  assert.doesNotMatch(page.html, /<ird>/, "raw file name must not reach the HTML unescaped");
});

test("visualize_graph atlas writes an index plus one page per major directory", async () => {
  const root = makeProject();
  const result = await callTool("visualize_graph", { atlas: true, open_browser: false, project_root: root });
  assert.equal(result.isError, undefined, resultText(result));

  const dir = join(root, "codebase_atlas");
  assert.deepEqual(readdirSync(dir).sort(), ["all.html", "core.html", "index.html", "ui.html"]);

  const index = readFileSync(join(dir, "index.html"), "utf-8");
  assert.match(index, /generated by codebase-graph-mcp/);
  assert.match(index, /href="all\.html"/);
  assert.match(index, /href="core\.html"/);
  assert.match(index, /href="ui\.html"/);
  assert.doesNotMatch(index, /tests\.html/);
  assert.match(index, /Most imported files/);
  assert.match(index, /No runtime circular dependencies/);
  assert.match(readFileSync(join(dir, "core.html"), "utf-8"), /"id": "core\/a\.ts"/);

  // running again overwrites the tool's own files
  const again = await callTool("visualize_graph", { atlas: true, open_browser: false, project_root: root });
  assert.equal(again.isError, undefined);
});

test("visualize_graph atlas refuses foreign files and .html output, writing nothing", async () => {
  const root = makeProject();
  mkdirSync(join(root, "docs"));
  writeFileSync(join(root, "docs", "index.html"), "<p>my own page</p>\n");

  const foreign = await callTool("visualize_graph", { atlas: true, output: "docs", open_browser: false, project_root: root });
  assert.equal(foreign.isError, true);
  assert.match(resultText(foreign), /not generated by this tool/);
  assert.equal(readFileSync(join(root, "docs", "index.html"), "utf-8"), "<p>my own page</p>\n");
  assert.equal(existsSync(join(root, "docs", "all.html")), false, "nothing is written when one target is refused");

  const asFile = await callTool("visualize_graph", { atlas: true, output: "atlas.html", open_browser: false, project_root: root });
  assert.equal(asFile.isError, true);
  assert.match(resultText(asFile), /output is a directory/);

  const outside = await callTool("visualize_graph", { atlas: true, output: "../escape", open_browser: false, project_root: root });
  assert.equal(outside.isError, true);
  assert.match(resultText(outside), /outside project root/);
});
