#!/usr/bin/env python3
"""codebase-pulse: show which project files a running Python program is in.

Run a program under it and open the printed URL:

    python codebase_pulse.py --root . --pages tmp/atlas -m package.module [args...]
    python codebase_pulse.py --root . --pages tmp/atlas -c package.module:main [args...]
    python codebase_pulse.py --root . --pages tmp/atlas script.py [args...]

A background thread samples the call stacks about 20 times a second and
streams the project files found on them to the graph pages generated by
codebase-graph-mcp, which light up the matching nodes.

What leaves the process: file paths relative to --root, nothing else. No
source lines, no variable values, no arguments. The server listens on
127.0.0.1 only and every request needs the random token printed at startup.

Standard library only; Python 3.8+.
"""

import argparse
import collections
import http.server
import json
import os
import queue
import runpy
import secrets
import socketserver
import sys
import threading
import time
import urllib.parse

__all__ = ["start", "main"]

SAMPLE_INTERVAL = 0.05  # seconds
MAX_CHAIN = 14  # project files kept per stack, innermost last
MAX_CHAINS = 8  # stacks reported per sample
HOLD_HEARTBEAT = 0.5  # unchanged "waiting" state is re-sent this often
BUFFER_EVENTS = 6000  # about five minutes of activity for replay
_OWN_FILE = os.path.realpath(__file__)
_SKIP_PARTS = ("site-packages", "dist-packages", "node_modules", ".venv", "venv", ".tox")


class Hub:
    """Fan-out of sampler events to SSE clients, with a replay buffer."""

    def __init__(self):
        self.lock = threading.Lock()
        self.clients = []
        self.buffer = collections.deque(maxlen=BUFFER_EVENTS)

    def publish(self, event):
        line = json.dumps(event, separators=(",", ":"))
        with self.lock:
            self.buffer.append((event["t"], line))
            clients = list(self.clients)
        for q in clients:
            try:
                q.put_nowait(line)
            except queue.Full:
                pass  # a stalled browser tab must never slow the program down

    def subscribe(self, replay_ms, now_ms):
        q = queue.Queue(maxsize=2000)
        with self.lock:
            backlog = [line for t, line in self.buffer if replay_ms and t >= now_ms - replay_ms]
            self.clients.append(q)
        return q, backlog

    def unsubscribe(self, q):
        with self.lock:
            if q in self.clients:
                self.clients.remove(q)


class Sampler(threading.Thread):
    """Samples every thread's stack and every parked asyncio task."""

    def __init__(self, root, hub, interval=SAMPLE_INTERVAL):
        super().__init__(name="codebase-pulse-sampler", daemon=True)
        self.root = os.path.realpath(root)
        self.prefix = self.root + os.sep
        self.hub = hub
        self.interval = interval
        self.started = time.monotonic()
        self.rel_cache = {}
        self.known_modules = set()
        self.loops = {}  # thread id -> running asyncio event loop
        self.last_hold = None
        self.last_hold_sent = 0.0
        self.stop_event = threading.Event()

    def now_ms(self):
        return int((time.monotonic() - self.started) * 1000)

    # -- path handling -------------------------------------------------------

    def rel(self, filename):
        """Project-relative path with forward slashes, or None for foreign code."""
        cached = self.rel_cache.get(filename, 0)
        if cached != 0:
            return cached
        result = None
        if filename and not filename.startswith("<"):
            try:
                real = os.path.realpath(filename)
            except (OSError, ValueError):
                real = ""
            if real.startswith(self.prefix) and real != _OWN_FILE:
                rel = real[len(self.prefix):]
                parts = rel.split(os.sep)
                if not any(p in _SKIP_PARTS for p in parts):
                    result = "/".join(parts)
        self.rel_cache[filename] = result
        return result

    def chain_from_frame(self, frame, tid=None):
        """Project files on a stack, outermost first, consecutive repeats merged."""
        out = []
        while frame is not None:
            code = frame.f_code
            rel = self.rel(code.co_filename)
            if rel and (not out or out[-1] != rel):
                out.append(rel)
            elif tid is not None and code.co_name == "run_forever" and tid not in self.loops:
                self.remember_loop(tid, frame)
            frame = frame.f_back
        out.reverse()
        return out[-MAX_CHAIN:]

    def remember_loop(self, tid, frame):
        """A thread inside BaseEventLoop.run_forever: keep its loop to list its tasks."""
        if not frame.f_code.co_filename.replace("\\", "/").endswith("asyncio/base_events.py"):
            return
        try:
            loop = frame.f_locals.get("self")
        except Exception:
            return
        if loop is not None and hasattr(loop, "is_closed"):
            self.loops[tid] = loop

    def chain_from_task(self, task):
        """Where a suspended asyncio task is parked: its await chain."""
        out = []
        coro = task.get_coro()
        seen = 0
        while coro is not None and seen < 64:
            seen += 1
            frame = getattr(coro, "cr_frame", None) or getattr(coro, "gi_frame", None) or getattr(coro, "ag_frame", None)
            if frame is not None:
                rel = self.rel(frame.f_code.co_filename)
                if rel and (not out or out[-1] != rel):
                    out.append(rel)
            coro = getattr(coro, "cr_await", None) or getattr(coro, "gi_yieldfrom", None) or getattr(coro, "ag_await", None)
        return out[-MAX_CHAIN:]

    # -- sampling ------------------------------------------------------------

    def parked_tasks(self, live_threads):
        asyncio = sys.modules.get("asyncio")
        if asyncio is None or not self.loops:
            return []
        chains = []
        for tid, loop in list(self.loops.items()):
            if tid not in live_threads or loop.is_closed():
                del self.loops[tid]
                continue
            try:
                for task in asyncio.all_tasks(loop):
                    if task.done() or getattr(task.get_coro(), "cr_running", False):
                        continue  # finished, or on a thread stack right now
                    chain = self.chain_from_task(task)
                    if chain:
                        chains.append(chain)
            except Exception:
                continue  # the task set changed under us; the next sample will do
        return chains

    def new_imports(self):
        if len(sys.modules) == len(self.known_modules):
            return []
        found = []
        for name, module in list(sys.modules.items()):
            if name in self.known_modules:
                continue
            self.known_modules.add(name)
            rel = self.rel(getattr(module, "__file__", None) or "")
            if rel:
                found.append(rel)
        return found

    def sample(self, previous):
        own = threading.get_ident()
        active, hold = [], []
        current = {}
        frames = sys._current_frames()
        for tid, frame in frames.items():
            if tid == own:
                continue
            chain = self.chain_from_frame(frame, tid)
            if not chain:
                continue
            # A thread whose innermost frame has not advanced since the last
            # sample is blocked (I/O, a lock, a sleep): parked, not working.
            signature = (id(frame), frame.f_lasti)
            current[tid] = signature
            (active if previous.get(tid) != signature else hold).append(chain)
        previous.clear()
        previous.update(current)

        hold.extend(self.parked_tasks(frames.keys()))
        return _unique(active)[:MAX_CHAINS], _unique(hold)[:MAX_CHAINS]

    def run(self):
        previous = {}
        while not self.stop_event.is_set():
            tick = time.monotonic()
            try:
                active, hold = self.sample(previous)
                imports = self.new_imports()
                event = {"t": self.now_ms()}
                if active:
                    event["a"] = active
                if imports:
                    event["i"] = imports[:200]
                hold_key = json.dumps(hold)
                if hold and (hold_key != self.last_hold or tick - self.last_hold_sent >= HOLD_HEARTBEAT):
                    event["h"] = hold
                    self.last_hold = hold_key
                    self.last_hold_sent = tick
                if len(event) > 1:
                    self.hub.publish(event)
            except Exception:
                pass  # never let the observer disturb the program it observes
            self.stop_event.wait(max(0.0, self.interval - (time.monotonic() - tick)))


def _unique(chains):
    seen, out = set(), []
    for chain in chains:
        key = tuple(chain)
        if key not in seen:
            seen.add(key)
            out.append(chain)
    return out


class Handler(http.server.BaseHTTPRequestHandler):
    server_version = "codebase-pulse"
    protocol_version = "HTTP/1.1"

    def log_message(self, *args):  # keep the program's terminal clean
        pass

    # -- guards --------------------------------------------------------------

    def allowed(self, query):
        ctx = self.server.ctx
        # The Host check defeats DNS rebinding; the token defeats other local pages.
        host = (self.headers.get("Host") or "").lower()
        if host not in ctx["hosts"]:
            return False
        token = (query.get("token") or [""])[0]
        if not token:
            for part in (self.headers.get("Cookie") or "").split(";"):
                name, _, value = part.strip().partition("=")
                if name == "pulse_token":
                    token = value
        return secrets.compare_digest(token, ctx["token"])

    def plain(self, status, text):
        body = text.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Connection", "close")
        self.end_headers()
        self.wfile.write(body)
        self.close_connection = True

    # -- routes --------------------------------------------------------------

    def do_GET(self):
        url = urllib.parse.urlsplit(self.path)
        query = urllib.parse.parse_qs(url.query)
        if not self.allowed(query):
            return self.plain(403, "forbidden")
        path = urllib.parse.unquote(url.path)
        if path == "/pulse/events":
            return self.events(query)
        if path == "/pulse/info":
            return self.info()
        if path in ("/", "/page", "/page/"):
            self.send_response(302)
            self.send_header("Location", "/page/" + self.server.ctx["landing"])
            self.send_header("Set-Cookie", self.cookie())
            self.send_header("Content-Length", "0")
            self.end_headers()
            return None
        if path.startswith("/page/"):
            return self.page(path[len("/page/"):])
        return self.plain(404, "not found")

    def cookie(self):
        return "pulse_token=%s; Path=/; HttpOnly; SameSite=Strict" % self.server.ctx["token"]

    def info(self):
        ctx = self.server.ctx
        body = json.dumps({
            "project": os.path.basename(ctx["sampler"].root),
            "pid": os.getpid(),
            "interval_ms": int(ctx["sampler"].interval * 1000),
            "uptime_ms": ctx["sampler"].now_ms(),
        }).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def page(self, name):
        pages = self.server.ctx["pages"]
        # Flat directory of generated .html files: no sub-paths, nothing else.
        if not pages or "/" in name or "\\" in name or not name.endswith(".html"):
            return self.plain(404, "not found")
        full = os.path.realpath(os.path.join(pages, name))
        if os.path.dirname(full) != pages or not os.path.isfile(full):
            return self.plain(404, "not found")
        with open(full, "rb") as handle:
            body = handle.read()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Set-Cookie", self.cookie())
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
        return None

    def events(self, query):
        ctx = self.server.ctx
        try:
            replay_s = max(0.0, min(300.0, float((query.get("replay") or ["0"])[0])))
        except ValueError:
            replay_s = 0.0
        q, backlog = ctx["hub"].subscribe(int(replay_s * 1000), ctx["sampler"].now_ms())
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True
        try:
            if backlog:
                self.wfile.write(("event: replay\ndata: [%s]\n\n" % ",".join(backlog)).encode("utf-8"))
                self.wfile.flush()
            while True:
                try:
                    line = q.get(timeout=10)
                    self.wfile.write(("data: %s\n\n" % line).encode("utf-8"))
                except queue.Empty:
                    self.wfile.write(b": keep-alive\n\n")
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError, OSError):
            pass
        finally:
            ctx["hub"].unsubscribe(q)


class Server(http.server.ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def server_bind(self):
        # HTTPServer.server_bind() calls socket.getfqdn(), a reverse DNS lookup
        # that can block for half a minute behind some resolvers. The name is
        # never used here, so bind without it.
        socketserver.TCPServer.server_bind(self)
        self.server_name, self.server_port = self.server_address[:2]


def _bind(port):
    candidates = [0] if port == 0 else range(port, port + 20)
    last_error = None
    for candidate in candidates:
        try:
            return Server(("127.0.0.1", candidate), Handler)
        except OSError as error:
            last_error = error
    raise last_error


def start(root=".", pages=None, port=8765, interval=SAMPLE_INTERVAL):
    """Start sampling and serving; returns the URL to open. Safe to call once."""
    hub = Hub()
    sampler = Sampler(root, hub, interval)
    server = _bind(port)
    bound = server.server_address[1]
    token = secrets.token_urlsafe(18)

    pages_dir = os.path.realpath(pages) if pages else None
    if pages_dir and not os.path.isdir(pages_dir):
        raise SystemExit("codebase-pulse: --pages %s is not a directory" % pages)
    landing = "index.html"
    if pages_dir and not os.path.isfile(os.path.join(pages_dir, landing)):
        htmls = sorted(f for f in os.listdir(pages_dir) if f.endswith(".html"))
        landing = htmls[0] if htmls else landing

    server.ctx = {
        "hub": hub,
        "sampler": sampler,
        "token": token,
        "pages": pages_dir,
        "landing": landing,
        "hosts": {"127.0.0.1:%d" % bound, "localhost:%d" % bound},
    }
    sampler.start()
    threading.Thread(target=server.serve_forever, name="codebase-pulse-http", daemon=True).start()
    return "http://127.0.0.1:%d/?token=%s" % (bound, token)


def _run_target(target_kind, target, args):
    here = os.path.dirname(_OWN_FILE)
    sys.path[:] = [p for p in sys.path if os.path.realpath(p or ".") != here]
    if target_kind == "module":
        sys.path.insert(0, os.getcwd())
        sys.argv = [target] + args
        runpy.run_module(target, run_name="__main__", alter_sys=True)
    elif target_kind == "call":
        module_name, _, func_name = target.partition(":")
        sys.path.insert(0, os.getcwd())
        sys.argv = [module_name] + args
        module = __import__(module_name, fromlist=[func_name or "main"])
        result = getattr(module, func_name or "main")()
        if isinstance(result, int):
            raise SystemExit(result)
    else:
        script = os.path.realpath(target)
        sys.path.insert(0, os.path.dirname(script))
        sys.argv = [target] + args
        runpy.run_path(script, run_name="__main__")


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="codebase_pulse.py",
        description="Run a Python program and stream which project files it is executing to the codebase-graph pages.",
    )
    parser.add_argument("--root", default=".", help="project root the graph was built from (default: current directory)")
    parser.add_argument("--pages", help="directory with generated graph pages to serve (an atlas folder)")
    parser.add_argument("--port", type=int, default=8765, help="port on 127.0.0.1 (default 8765, next free one if taken; 0 = any)")
    parser.add_argument("--open", action="store_true", help="open the live page in the default browser")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-m", dest="module", help="run a module, like python -m")
    group.add_argument("-c", dest="call", metavar="MODULE:FUNC", help="import MODULE and call FUNC(), like a console script")
    parser.add_argument("rest", nargs=argparse.REMAINDER, help="[script.py] and the program's own arguments")
    options = parser.parse_args(argv)

    rest = list(options.rest)
    if rest and rest[0] == "--":
        rest.pop(0)
    if options.module:
        kind, target = "module", options.module
    elif options.call:
        kind, target = "call", options.call
    elif rest:
        kind, target = "script", rest.pop(0)
    else:
        parser.error("nothing to run: give -m MODULE, -c MODULE:FUNC or a script path")

    url = start(options.root, options.pages, options.port)
    sys.stderr.write("[pulse] live graph: %s\n" % url)
    sys.stderr.flush()
    if options.open:
        try:
            import webbrowser
            webbrowser.open(url)
        except Exception:
            pass

    _run_target(kind, target, rest)


if __name__ == "__main__":
    main()
