import { relative, basename } from "node:path";
import { detectCycles, getProjectOverview, isRuntimeEdge, type GraphData } from "./graph.js";
import { PULSE_CSS, PULSE_GRAPH_JS, PULSE_INDEX_JS, PULSE_PILL_HTML } from "./pulse-client.js";

// Marks HTML this server wrote, so it only ever overwrites its own output.
export const GENERATED_MARKER = "<!-- generated by codebase-graph-mcp -->";

// Pinned so a CDN release can neither break nor silently change the page.
const VIS_NETWORK_URL = "https://cdn.jsdelivr.net/npm/vis-network@10.1.2/standalone/umd/vis-network.min.js";
const VIS_NETWORK_SRI = "sha384-RDdG1CLOxjNlTHh4JYx/rnAueaMHbkBHmeHwrEyljMQw3LF0it4SkuNotIY/FPxD";

// Categorical slots as [light, dark]. The order is the colour-blind safety
// mechanism (adjacent pairs validated on both surfaces), so slots are handed
// out in this order and never cycled: a ninth directory folds into "Other".
const SERIES: [string, string][] = [
  ["#2a78d6", "#3987e5"], // blue
  ["#eb6834", "#d95926"], // orange
  ["#1baf7a", "#199e70"], // aqua
  ["#eda100", "#c98500"], // yellow
  ["#e87ba4", "#d55181"], // magenta
  ["#008300", "#008300"], // green
  ["#4a3aa7", "#9085e9"], // violet
  ["#e34948", "#e66767"], // red
];
const OTHER: [string, string] = ["#898781", "#898781"];
const OTHER_GROUP = "Other";

// Shared tokens: neutral surfaces and ink, one accent, one reserved status colour.
const THEME_CSS = `
  :root {
    color-scheme: light;
    --page: #f9f9f7; --surface: #fcfcfb; --surface-2: #ffffff;
    --ink: #0b0b0b; --ink-2: #52514e; --muted: #898781;
    --hairline: #e1e0d9; --edge: #c3c2b7; --accent: #2a78d6; --critical: #d03b3b; --good: #0ca30c;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      color-scheme: dark;
      --page: #0d0d0d; --surface: #1a1a19; --surface-2: #232322;
      --ink: #ffffff; --ink-2: #c3c2b7; --muted: #898781;
      --hairline: #2c2c2a; --edge: #4a4a46; --accent: #3987e5; --critical: #e0605f;
    }
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--page); color: var(--ink); font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }
  code, .mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  a { color: var(--accent); }
${PULSE_CSS}`;

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// JSON for an inline <script>: no character that the HTML parser could read
// as markup (`</script`, `<!--`, `<script`) or that ends a JS line survives.
function safeJsonForScript(obj: unknown): string {
  return JSON.stringify(obj, null, 2).replace(
    /[<>&\u2028\u2029]/g,
    (ch) => "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0"),
  );
}

function scopePrefixOf(scope?: string): string {
  return scope ? scope.replace(/\/+$/, "") + "/" : "";
}

const formatCount = (n: number): string => n.toLocaleString("en-US");

export interface GraphPage {
  html: string;
  nodeCount: number;
  edgeCount: number;
  // most imported files in the page, as [relative path, importer count]
  topFiles: [string, number][];
}

interface PageNode {
  id: string;
  label: string;
  value: number;
  group: string;
  importers: number;
  importsInView: number;
  // files in the page that import this one and are imported by it at runtime
  mutual: string[];
}

/**
 * One interactive graph page: the `top` most imported files under `scope`
 * (whole project when empty) and the edges between them.
 *
 * Encoding: node size = number of importers, fill = directory below the
 * scope, a red double-headed edge = two files that import each other at
 * runtime (the smallest, most fixable kind of cycle). Every node is labelled
 * and listed in the table view, so colour never carries identity alone.
 * `backLink` adds a link to an atlas index.
 */
export function buildGraphPage(
  graph: GraphData,
  root: string,
  options: { scope?: string; top: number; backLink?: string },
): GraphPage {
  const { scope, top, backLink } = options;
  const prefix = scopePrefixOf(scope);

  // Scope first, then rank: "top 30 in gateway/", not "gateway files among the global top 30"
  // Every tracked file is a candidate, so on a small project the entry points
  // (imported by nobody) still get a node; on a large one they rank last.
  const sorted = [...graph.files]
    .filter((file) => !prefix || relative(root, file).startsWith(prefix))
    .map((file) => [file, graph.dependents.get(file)?.size ?? 0] as [string, number])
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, top);
  const topSet = new Set(sorted.map(([f]) => f));

  // A pair importing each other at runtime is drawn once, as a mutual edge
  const edges: { from: string; to: string; mutual?: boolean }[] = [];
  const importsInView = new Map<string, number>();
  const mutualWith = new Map<string, string[]>();
  let dependencyCount = 0;
  for (const file of topSet) {
    for (const dep of graph.dependencies.get(file) || []) {
      if (!topSet.has(dep)) continue;
      dependencyCount++;
      importsInView.set(file, (importsInView.get(file) || 0) + 1);
      const mutual = isRuntimeEdge(graph, file, dep) && isRuntimeEdge(graph, dep, file);
      if (mutual) {
        mutualWith.set(file, [...(mutualWith.get(file) || []), relative(root, dep)]);
        if (file > dep) continue; // the reverse direction already drew it
      }
      edges.push(mutual ? { from: relative(root, file), to: relative(root, dep), mutual: true } : { from: relative(root, file), to: relative(root, dep) });
    }
  }
  const mutualPairs = edges.filter((e) => e.mutual).length;

  // Group = first directory below the scope; files directly in it share one group
  const looseGroup = scope ? `${scope.replace(/\/+$/, "")}/*` : "(root files)";
  const groupOf = (relPath: string): string => {
    const parts = relPath.slice(prefix.length).split("/");
    return parts.length === 1 ? looseGroup : parts[0];
  };

  const shortName = (rel: string): string => rel.replace(/\.(py|tsx?|jsx?|mjs|cjs|mts|cts|rs)$/, "").split("/").pop() || rel;
  const nameCounts = new Map<string, number>();
  for (const [file] of sorted) {
    const name = shortName(relative(root, file));
    nameCounts.set(name, (nameCounts.get(name) || 0) + 1);
  }

  const nodes: PageNode[] = sorted.map(([file, count]) => {
    const rel = relative(root, file);
    const name = shortName(rel);
    // Two `config` or `index` files in one graph get their directory as well
    const parent = rel.split("/").slice(-2, -1)[0];
    return {
      id: rel,
      label: (nameCounts.get(name) || 0) > 1 && parent ? `${parent}/${name}` : name,
      value: Math.max(count, 1),
      group: groupOf(rel),
      importers: count,
      importsInView: importsInView.get(file) || 0,
      mutual: mutualWith.get(file) || [],
    };
  });

  // Colour follows the directory, not its rank: slots go to groups in
  // alphabetical order. With more groups than slots, the biggest keep a colour.
  const groupSizes = new Map<string, number>();
  for (const n of nodes) groupSizes.set(n.group, (groupSizes.get(n.group) || 0) + 1);
  let named = [...groupSizes.keys()];
  if (named.length > SERIES.length) {
    named = named.sort((a, b) => groupSizes.get(b)! - groupSizes.get(a)! || a.localeCompare(b)).slice(0, SERIES.length - 1);
  }
  // Alphabetical, with the scope's own loose files always in the first slot
  named.sort((a, b) => (a === looseGroup ? -1 : b === looseGroup ? 1 : a.localeCompare(b)));
  const groups = named.map((name, i) => ({ name, light: SERIES[i][0], dark: SERIES[i][1] }));
  const namedSet = new Set(named);
  if (namedSet.size < groupSizes.size) groups.push({ name: OTHER_GROUP, light: OTHER[0], dark: OTHER[1] });
  for (const n of nodes) if (!namedSet.has(n.group)) n.group = OTHER_GROUP;

  const project = basename(root);
  const heading = scope ? scope.replace(/\/+$/, "") + "/" : project;

  const legendGroups =
    groups.length > 1
      ? groups
          .map(
            (g) =>
              `<span class="key"><i class="swatch" style="--l:${g.light};--d:${g.dark}"></i>${escapeHtml(g.name)} <span class="n">${groupSizes.get(g.name) ?? nodes.filter((n) => n.group === g.name).length}</span></span>`,
          )
          .join("")
      : "";
  const legendMutual = mutualPairs > 0 ? `<span class="key"><i class="mutual"></i>&#9888; import each other <span class="n">${mutualPairs}</span></span>` : "";

  const tableRows = nodes
    .map(
      (n) =>
        `<tr><td class="mono">${escapeHtml(n.id)}</td><td>${escapeHtml(n.group)}</td><td class="num">${n.importers}</td><td class="num">${n.importsInView}</td><td class="mono">${n.mutual.length ? "&#9888; " + n.mutual.map(escapeHtml).join(", ") : ""}</td></tr>`,
    )
    .join("\n");
  const datalist = nodes.map((n) => `<option value="${escapeHtml(n.id)}">`).join("");

  const html = `<!DOCTYPE html>
${GENERATED_MARKER}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Codebase Graph - ${escapeHtml(project)}${scope ? ` - ${escapeHtml(scope)}` : ""}</title>
<script src="${VIS_NETWORK_URL}" integrity="${VIS_NETWORK_SRI}" crossorigin="anonymous"></script>
<style>${THEME_CSS}
  header { padding: 14px 20px 12px; background: var(--surface); border-bottom: 1px solid var(--hairline); }
  .bar { display: flex; flex-wrap: wrap; align-items: baseline; gap: 6px 16px; }
  .back { text-decoration: none; font-size: 14px; }
  h1 { margin: 0; font-size: 18px; font-weight: 650; }
  .sub { color: var(--ink-2); font-size: 13px; }
  .tools { margin-left: auto; display: inline-flex; flex-wrap: wrap; gap: 8px; align-items: center; }
  #live { padding: 6px 12px; font: inherit; font-size: 13px; color: var(--ink-2); background: var(--surface-2); border: 1px solid var(--hairline); border-radius: 8px; cursor: pointer; }
  #live:hover { color: var(--ink); }
  #live[aria-pressed="true"] { color: #fff; background: var(--accent); border-color: var(--accent); }
  #live:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
  #find { width: 240px; max-width: 100%; padding: 6px 10px; font: inherit; font-size: 13px; color: var(--ink); background: var(--surface-2); border: 1px solid var(--hairline); border-radius: 8px; }
  #find:focus { outline: 2px solid var(--accent); outline-offset: 1px; }
  .legend { display: flex; flex-wrap: wrap; gap: 6px 18px; margin-top: 10px; font-size: 12.5px; color: var(--ink-2); }
  .key { display: inline-flex; align-items: center; gap: 6px; white-space: nowrap; }
  .key .n { color: var(--muted); }
  .swatch { width: 10px; height: 10px; border-radius: 50%; background: var(--l); }
  .mutual { width: 18px; height: 0; border-top: 2.5px solid var(--critical); }
  .size { display: inline-flex; align-items: center; gap: 3px; }
  .size i { border-radius: 50%; background: var(--muted); }
  @media (prefers-color-scheme: dark) { .swatch { background: var(--d); } }
  #graph { width: 100%; height: calc(100vh - 150px); min-height: 440px; background: var(--page); }
  details { margin: 0 20px 28px; font-size: 13px; }
  summary { cursor: pointer; padding: 12px 0; color: var(--ink-2); }
  .scroll { overflow-x: auto; }
  table { border-collapse: collapse; width: 100%; }
  th, td { text-align: left; padding: 6px 12px 6px 0; border-bottom: 1px solid var(--hairline); }
  th { color: var(--ink-2); font-weight: 500; }
  td.mono { font-size: 12.5px; overflow-wrap: anywhere; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  div.vis-tooltip { background: var(--surface-2); color: var(--ink); border: 1px solid var(--hairline); border-radius: 8px; padding: 8px 10px; font: 12.5px/1.45 system-ui, -apple-system, sans-serif; box-shadow: 0 4px 16px rgba(0,0,0,.18); }
  .tip-path { font-family: ui-monospace, Menlo, monospace; font-size: 12px; margin-bottom: 4px; }
  .tip-dim { color: var(--ink-2); }
  .tip-warn { color: var(--critical); margin-top: 4px; }
</style>
</head>
<body>
<header>
  <div class="bar">
    ${backLink ? `<a class="back" href="${escapeHtml(backLink)}">&larr; index</a>` : ""}
    <h1>${escapeHtml(heading)}</h1>
    <span class="sub">${scope ? `${escapeHtml(project)} &middot; ` : ""}${nodes.length} most imported files &middot; ${dependencyCount} dependencies between them</span>
    ${PULSE_PILL_HTML}
    <span class="tools">
      <button id="live" type="button" aria-pressed="false" title="Let the layout keep moving: drag a file and its cluster follows">Live layout</button>
      <input id="find" type="search" list="files" placeholder="Find a file&hellip;" aria-label="Find a file in the graph">
    </span>
    <datalist id="files">${datalist}</datalist>
  </div>
  <div class="legend">
    ${legendGroups}
    ${legendMutual}
    <span class="key"><span class="size"><i style="width:6px;height:6px"></i><i style="width:10px;height:10px"></i><i style="width:14px;height:14px"></i></span>size = files importing it</span>
    <span class="key">click a file to isolate its neighbours</span>
  </div>
</header>
<div id="graph" role="img" aria-label="Dependency graph of ${nodes.length} files; the same data is in the table below"></div>
<details>
  <summary>Table view (${nodes.length} files)</summary>
  <div class="scroll"><table>
    <thead><tr><th>File</th><th>Group</th><th class="num">Imported by</th><th class="num">Imports shown</th><th>Imports each other with</th></tr></thead>
    <tbody>
${tableRows}
    </tbody>
  </table></div>
</details>
<script>
  var DATA = ${safeJsonForScript({ nodes, edges, groups })};

  var css = function (name) { return getComputedStyle(document.documentElement).getPropertyValue(name).trim(); };
  var dark = function () { return window.matchMedia("(prefers-color-scheme: dark)").matches; };
  var fillOf = function (group) {
    var g = DATA.groups.find(function (x) { return x.name === group; });
    return g ? (dark() ? g.dark : g.light) : css("--muted");
  };

  function tooltip(n) {
    var box = document.createElement("div");
    var add = function (cls, text) { var d = document.createElement("div"); d.className = cls; d.textContent = text; box.appendChild(d); };
    add("tip-path", n.id);
    add("", "Imported by " + n.importers + " file" + (n.importers === 1 ? "" : "s"));
    add("tip-dim", "Imports " + n.importsInView + " of the files shown here");
    if (n.mutual.length) add("tip-warn", "\\u26A0 Imports each other with: " + n.mutual.join(", "));
    return box;
  }

  function nodeStyle(n, faded) {
    var fill = fillOf(n.group);
    return {
      id: n.id,
      opacity: faded ? 0.12 : 1,
      borderWidth: 2,
      color: { background: fill, border: css("--page"), highlight: { background: fill, border: css("--ink") }, hover: { background: fill, border: css("--ink") } },
      font: { color: faded ? "rgba(128,128,128,0.25)" : css("--ink"), strokeColor: css("--page") },
    };
  }

  var nodes = new vis.DataSet(DATA.nodes.map(function (n) {
    var styled = nodeStyle(n, false);
    styled.label = n.label; styled.value = n.value; styled.title = tooltip(n);
    return styled;
  }));
  function edgeStyle(e, i) {
    if (!e.mutual) return { id: i, from: e.from, to: e.to };
    var red = css("--critical");
    return { id: i, from: e.from, to: e.to, width: 2.2, arrows: "to, from", color: { color: red, hover: red, highlight: red, opacity: 1 } };
  }
  var edges = new vis.DataSet(DATA.edges.map(edgeStyle));

  var network = new vis.Network(document.getElementById("graph"), { nodes: nodes, edges: edges }, {
    nodes: {
      shape: "dot",
      scaling: { min: 7, max: 44, label: { enabled: true, min: 12, max: 26, drawThreshold: 5, maxVisible: 30 } },
      font: { face: "system-ui, -apple-system, sans-serif", strokeWidth: 4 },
    },
    edges: {
      width: 1, hoverWidth: 0.6, selectionWidth: 1.2,
      arrows: { to: { enabled: true, scaleFactor: 0.45 } },
      smooth: { type: "continuous", roundness: 0.35 },
      color: { color: css("--edge"), hover: css("--ink-2"), highlight: css("--ink"), opacity: 0.75 },
    },
    physics: {
      solver: "forceAtlas2Based",
      // Bigger graphs need more repulsion or the hubs pile up and their labels collide
      forceAtlas2Based: { gravitationalConstant: -Math.min(220, 70 + DATA.nodes.length * 0.7), centralGravity: 0.014, springLength: 130, springConstant: 0.05, damping: 0.55, avoidOverlap: 0.8 },
      stabilization: { iterations: 350 },
    },
    interaction: { hover: true, tooltipDelay: 90, zoomView: true, dragView: true },
  });

  // Freeze the layout once it settles: a graph that keeps drifting is hard to read.
  network.once("stabilizationIterationsDone", function () {
    network.setOptions({ physics: { enabled: false } });
    network.fit({ animation: false });
  });

  // Off by default so the page opens still; on, dragging a file pulls its cluster along.
  var live = document.getElementById("live");
  live.addEventListener("click", function () {
    var on = live.getAttribute("aria-pressed") !== "true";
    live.setAttribute("aria-pressed", String(on));
    network.setOptions({ physics: { enabled: on } });
    if (on) network.startSimulation();
  });

  var focused = null;
  function applyFocus(id) {
    focused = id;
    var keep = null;
    if (id !== null) {
      keep = new Set(network.getConnectedNodes(id));
      keep.add(id);
    }
    nodes.update(DATA.nodes.map(function (n) { return nodeStyle(n, keep !== null && !keep.has(n.id)); }));
    var connected = id === null ? null : new Set(network.getConnectedEdges(id));
    edges.update(edges.getIds().map(function (eid) {
      var on = connected === null || connected.has(eid);
      return { id: eid, hidden: !on };
    }));
  }
  network.on("selectNode", function (p) { applyFocus(p.nodes[0]); });
  network.on("deselectNode", function () { applyFocus(null); });

  var find = document.getElementById("find");
  find.addEventListener("change", function () {
    var q = find.value.trim().toLowerCase();
    if (!q) { network.unselectAll(); applyFocus(null); return; }
    var hit = DATA.nodes.find(function (n) { return n.id.toLowerCase() === q; }) ||
              DATA.nodes.find(function (n) { return n.id.toLowerCase().indexOf(q) >= 0; });
    if (!hit) return;
    network.selectNodes([hit.id]);
    applyFocus(hit.id);
    network.focus(hit.id, { scale: 1.1, animation: { duration: 400 } });
  });

  // Follow the OS theme without a reload
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", function () {
    network.setOptions({ edges: { color: { color: css("--edge"), hover: css("--ink-2"), highlight: css("--ink"), opacity: 0.75 } } });
    edges.update(DATA.edges.map(edgeStyle));
    applyFocus(focused);
  });
${PULSE_GRAPH_JS}</script>
</body>
</html>`;

  return {
    html,
    nodeCount: nodes.length,
    edgeCount: dependencyCount,
    topFiles: sorted.map(([f, c]) => [relative(root, f), c]),
  };
}

export interface AtlasScope {
  // directory relative to the project root, e.g. "gateway" or "apps/desktop/src/store"
  scope: string;
  files: number;
  // how many imports point into this directory
  importers: number;
}

/**
 * The directories worth a graph of their own: direct children of `base`
 * ranked by how often their files are imported. Test-only or leaf
 * directories whose files nobody imports drop out on their own.
 */
export function pickAtlasScopes(graph: GraphData, root: string, base: string | undefined, maxScopes: number): AtlasScope[] {
  const prefix = scopePrefixOf(base);
  const stats = new Map<string, { files: number; importers: number; imported: number }>();

  for (const file of graph.files) {
    const rel = relative(root, file);
    if (prefix && !rel.startsWith(prefix)) continue;
    const parts = rel.slice(prefix.length).split("/");
    if (parts.length < 2) continue; // a file directly in base, not a directory
    const scope = prefix + parts[0];
    const entry = stats.get(scope) ?? { files: 0, importers: 0, imported: 0 };
    const dependents = graph.dependents.get(file)?.size ?? 0;
    entry.files++;
    entry.importers += dependents;
    if (dependents > 0) entry.imported++;
    stats.set(scope, entry);
  }

  return [...stats.entries()]
    .filter(([, s]) => s.imported >= 2) // fewer than two connected files is not a graph
    .sort((a, b) => b[1].importers - a[1].importers)
    .slice(0, maxScopes)
    .map(([scope, s]) => ({ scope, files: s.files, importers: s.importers }));
}

export function atlasFileName(scope: string): string {
  return scope.replace(/[^\w.-]+/g, "_") + ".html";
}

export interface AtlasEntry {
  title: string;
  href: string;
  // directory the page covers; empty for the whole-project page
  scope?: string;
  files?: number;
  importers?: number;
  page: GraphPage;
}

// A ranked list with thin bars: file name, bar proportional to the count, value.
function barList(items: [string, number][], stripPrefix: string, shorten = true): string {
  const max = Math.max(1, ...items.map(([, c]) => c));
  return items
    .filter(([, count]) => count > 0)
    .map(([file, count]) => {
      // Keep the informative end of a long path: ".../i18n/index.ts"
      const local = stripPrefix && file.startsWith(stripPrefix) ? file.slice(stripPrefix.length) : file;
      const parts = local.split("/");
      const name = shorten && parts.length > 2 ? "\u2026/" + parts.slice(-2).join("/") : local;
      const width = Math.max(2, Math.round((count / max) * 100));
      return `<li title="${escapeHtml(file)}"><span class="name mono">${escapeHtml(name)}</span><span class="track"><span class="fill" style="width:${width}%"></span></span><span class="val">${formatCount(count)}</span></li>`;
    })
    .join("\n");
}

/** The atlas landing page: project totals, one card per graph, hotspots and cycles. */
export function buildAtlasIndex(graph: GraphData, root: string, base: string | undefined, entries: AtlasEntry[]): string {
  const overview = getProjectOverview(graph, root);
  const cycles = detectCycles(graph);
  const project = basename(root) + (base ? ` / ${base}` : "");
  const date = new Date().toISOString().slice(0, 10);

  const tiles = [
    [formatCount(overview.totalFiles), "source files"],
    [formatCount(overview.totalEdges), "import edges"],
    [formatCount(cycles.totalCycles), cycles.totalCycles === 1 ? "cycle group" : "cycle groups"],
    [formatCount(cycles.filesInCycles), "files inside a cycle group"],
  ]
    .map(([value, label]) => `<div class="tile"><div class="value">${value}</div><div class="label">${label}</div></div>`)
    .join("\n");

  const cards = entries
    .map((entry) => {
      const meta = [
        entry.files !== undefined ? `${formatCount(entry.files)} files` : "",
        entry.importers !== undefined ? `imported ${formatCount(entry.importers)} times` : "",
        `${entry.page.nodeCount} nodes, ${entry.page.edgeCount} edges`,
      ]
        .filter(Boolean)
        .join(" &middot; ");
      const list = barList(entry.page.topFiles.slice(0, 5), scopePrefixOf(entry.scope));
      return `<a class="card" href="${escapeHtml(entry.href)}" data-scope="${escapeHtml((entry.scope || "").replace(/\/+$/, ""))}">
  <div class="head"><span class="title">${escapeHtml(entry.title)}</span><span class="open">open graph &rarr;</span></div>
  <div class="meta">${meta}</div>
  <ul class="bars">
${list || `<li class="empty">no imported files</li>`}
  </ul>
</a>`;
    })
    .join("\n");

  const hotspots = barList(overview.mostImported.map((m) => [m.file, m.count] as [string, number]), "", false);

  const cycleItems = cycles.cycles
    .slice(0, 12)
    .map((cycle, i) => {
      const path = cycle.map((f) => escapeHtml(relative(root, f)));
      const group = cycles.groupSizes[i];
      const note = group > cycle.length ? `<span class="group">shortest loop in a group of ${formatCount(group)} mutually dependent files</span>` : "";
      return `<li><span class="badge">&#9888; ${formatCount(group)} file${group === 1 ? "" : "s"}</span><span class="chainwrap">${note}<span class="mono chain">${[...path, path[0]].join(" <span class=\"arrow\">&rarr;</span> ")}</span></span></li>`;
    })
    .join("\n");
  const cycleSection =
    cycles.totalCycles === 0
      ? `<p class="dim">No runtime circular dependencies.</p>`
      : `<ul class="cycles">\n${cycleItems}\n</ul>${cycles.totalCycles > 12 ? `\n<p class="dim">and ${cycles.totalCycles - 12} more</p>` : ""}`;

  return `<!DOCTYPE html>
${GENERATED_MARKER}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Codebase Atlas - ${escapeHtml(project)}</title>
<style>${THEME_CSS}
  body { padding: 40px 16px 64px; }
  main { max-width: 1080px; margin: 0 auto; }
  h1 { font-size: 26px; font-weight: 650; margin: 0 0 6px; letter-spacing: -0.01em; }
  h2 { font-size: 15px; font-weight: 600; margin: 40px 0 14px; color: var(--ink-2); text-transform: uppercase; letter-spacing: 0.06em; }
  .dim { color: var(--ink-2); font-size: 13.5px; margin: 0; }
  .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; margin: 26px 0 0; }
  .tile { background: var(--surface); border: 1px solid var(--hairline); border-radius: 12px; padding: 16px 18px; }
  .tile .value { font-size: 30px; font-weight: 650; letter-spacing: -0.02em; line-height: 1.1; }
  .tile .label { color: var(--ink-2); font-size: 13px; margin-top: 4px; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); gap: 14px; }
  a.card { display: block; padding: 18px 20px; background: var(--surface); border: 1px solid var(--hairline); border-radius: 12px; color: inherit; text-decoration: none; transition: border-color .12s, transform .12s; }
  a.card:hover, a.card:focus-visible { border-color: var(--accent); transform: translateY(-1px); outline: none; }
  a.card.hot { border-color: var(--good); box-shadow: 0 0 0 3px color-mix(in srgb, var(--good) 25%, transparent), 0 0 28px color-mix(in srgb, var(--good) 30%, transparent); }
  .livebar { margin-top: 10px; min-height: 18px; }
  .head { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; }
  .title { font-size: 17px; font-weight: 650; overflow-wrap: anywhere; }
  .open { font-size: 12.5px; color: var(--accent); white-space: nowrap; opacity: 0; transition: opacity .12s; }
  a.card:hover .open, a.card:focus-visible .open { opacity: 1; }
  .meta { color: var(--ink-2); font-size: 13px; margin: 4px 0 14px; }
  ul.bars { list-style: none; margin: 0; padding: 0; }
  ul.bars li { display: grid; grid-template-columns: minmax(0, 1.7fr) minmax(50px, 1fr) 44px; align-items: center; gap: 12px; padding: 4px 0; font-size: 12.5px; }
  ul.bars .name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  ul.bars .track { display: block; height: 6px; }
  ul.bars .fill { display: block; height: 100%; min-width: 3px; background: var(--accent); border-radius: 0 4px 4px 0; }
  ul.bars .val { text-align: right; color: var(--ink-2); font-variant-numeric: tabular-nums; }
  ul.bars .empty { display: block; color: var(--muted); }
  .panel { background: var(--surface); border: 1px solid var(--hairline); border-radius: 12px; padding: 16px 20px; }
  ul.cycles { list-style: none; margin: 0; padding: 0; }
  ul.cycles li { display: flex; gap: 12px; align-items: baseline; padding: 8px 0; border-bottom: 1px solid var(--hairline); font-size: 12.5px; }
  ul.cycles li:last-child { border-bottom: 0; }
  .badge { flex: none; min-width: 92px; color: var(--critical); font-weight: 600; white-space: nowrap; }
  .chainwrap { display: flex; flex-direction: column; gap: 3px; min-width: 0; }
  .group { color: var(--ink-2); font-size: 12.5px; }
  .chain { overflow-wrap: anywhere; line-height: 1.6; }
  .arrow { color: var(--muted); }
</style>
</head>
<body>
<main>
  <h1>${escapeHtml(project)}</h1>
  <p class="dim">Codebase atlas &middot; generated ${date}${graph.truncated ? " &middot; scan truncated" : ""}. In every graph a node is a file, its size is the number of files importing it, and a red double-headed edge joins two files that import each other.</p>

  <div class="livebar">${PULSE_PILL_HTML}</div>

  <div class="tiles">
${tiles}
  </div>

  <h2>Graphs</h2>
  <div class="cards">
${cards}
  </div>

  <h2>Most imported files</h2>
  <div class="panel"><ul class="bars">
${hotspots}
  </ul></div>

  <h2>Circular dependencies</h2>
  <div class="panel">${cycleSection}</div>
</main>
<script>
${PULSE_INDEX_JS}</script>
</body>
</html>`;
}
